### ISSUE TITLE
Android Gradle Build Errors 'com.algolia:algoliasearch-android:3.+'

### ISSUE THREAD

**Issue by flexpeace** [algolia/instantsearch-android-examples#16]
I just dropped this implementation 'com.algolia:algoliasearch-android:3.+' into my dependencies and l am getting the error below:

![agolia](https://user-images.githubusercontent.com/5002192/43765270-35844db4-9a38-11e8-8c14-e0b8ec385036.PNG)

The error disappears when l remove your library.  Can l get any help?

**Comment by flexpeace** [comment]
Issue Fixed

**Comment by PLNech** [comment]
Hi @flexpeace, thanks for reporting this and glad to read the issue disappeared!

Could you share what you did to fix the issue, so that it can help future readers? 

Let me know if I can help with anything else!

**Comment by flexpeace** [comment]
In the build.Gradle, I changed to the following 

compileSdkVersion 28
targetSdkVersion 28

Also l changed my Android dependencies to 28.0.0-rc01

e.g.
implementation 'com.android.support:appcompat-v7:28.0.0-rc01

**Comment by PLNech** [comment]
Thanks for these details! We indeed had an issue updating to v28 while it was still a beta in the release `3.22.15` of our API Client, downgrading back to v27.1.1 in `3.23`. 

You should not encounter this issue again; we'll upgrade to v28 as soon as the `rc01` becomes a true release.
