### ISSUE TITLE
Paging Single Index not showing any data

### ISSUE THREAD

**Issue by NainalChauhan** [algolia/instantsearch-android-examples#20]
I have build and run the example code and implemented the getting started guide in my own project but its not showing any data in recycler view. In your example also its is not working. Please look into the issue.

**Comment by q-litzler** [comment]
Hello,

I can't reproduce the problem on my side.
When running the Getting Started Guide, can you please look at your logcat and see if there's any error for each HTTP request ?

Thanks

**Comment by NainalChauhan** [comment]
![device-2019-09-10-152933](https://user-images.githubusercontent.com/26924554/64603758-7fb0bb80-d3de-11e9-8e9c-c2757db575e4.png)
![device-2019-09-10-153012](https://user-images.githubusercontent.com/26924554/64603779-88a18d00-d3de-11e9-90bd-9feb64a4a5c2.png)

As you can see in the screenshots , it is showing the number of hits but not the actual movies list.

**Comment by NainalChauhan** [comment]
I am testing on a real device, model:- Elite Swipe, OS version:- Marshmallow 

Steps to reproduce:-
Open app, navigate to "Paging Single Index" option and search for any keyword. It will show hits but not the list.

Here is the complete logcat :-

09-11 11:56:31.333 10847-11373/com.algolia.instantsearch.showcase I/System.out: HttpClient: REQUEST: https://latency-dsn.algolia.net/1/indexes/*/queries
09-11 11:56:31.333 10847-11373/com.algolia.instantsearch.showcase I/System.out: HttpClient: METHOD: HttpMethod(value=POST)
09-11 11:56:31.333 10847-11373/com.algolia.instantsearch.showcase I/System.out: HttpClient: COMMON HEADERS
09-11 11:56:31.333 10847-11373/com.algolia.instantsearch.showcase I/System.out: HttpClient: -> X-Algolia-Application-Id: latency
09-11 11:56:31.333 10847-11373/com.algolia.instantsearch.showcase I/System.out: HttpClient: -> X-Algolia-API-Key: 1f6fd3a6fb973cb08419fe7d288fa4db
09-11 11:56:31.333 10847-11373/com.algolia.instantsearch.showcase I/System.out: HttpClient: -> User-Agent: Android (23); InstantSearchAndroid (2.0.2); Algolia for Kotlin (1.1.4)
09-11 11:56:31.334 10847-11373/com.algolia.instantsearch.showcase I/System.out: HttpClient: -> Accept: application/json
09-11 11:56:31.334 10847-11373/com.algolia.instantsearch.showcase I/System.out: HttpClient: -> Accept-Charset: UTF-8
09-11 11:56:31.334 10847-11373/com.algolia.instantsearch.showcase I/System.out: HttpClient: CONTENT HEADERS
09-11 11:56:31.335 10847-11373/com.algolia.instantsearch.showcase I/art: Note: end time exceeds epoch: 
09-11 11:56:31.453 10847-11373/com.algolia.instantsearch.showcase I/System.out: HttpClient: RESPONSE: 200 OK
09-11 11:56:31.453 10847-11373/com.algolia.instantsearch.showcase I/System.out: HttpClient: METHOD: HttpMethod(value=POST)
09-11 11:56:31.454 10847-11373/com.algolia.instantsearch.showcase I/System.out: HttpClient: FROM: https://latency-dsn.algolia.net/1/indexes/*/queries
09-11 11:56:31.454 10847-11373/com.algolia.instantsearch.showcase I/System.out: HttpClient: COMMON HEADERS
09-11 11:56:31.454 10847-11373/com.algolia.instantsearch.showcase I/System.out: HttpClient: -> Accept-Encoding: deflate, gzip
09-11 11:56:31.454 10847-11373/com.algolia.instantsearch.showcase I/System.out: HttpClient: -> Access-Control-Allow-Origin: *
09-11 11:56:31.454 10847-11373/com.algolia.instantsearch.showcase I/System.out: HttpClient: -> Cache-Control: no-cache
09-11 11:56:31.454 10847-11373/com.algolia.instantsearch.showcase I/System.out: HttpClient: -> Connection: keep-alive
09-11 11:56:31.454 10847-11373/com.algolia.instantsearch.showcase I/System.out: HttpClient: -> Content-Disposition: inline; filename=a.txt
09-11 11:56:31.454 10847-11373/com.algolia.instantsearch.showcase I/System.out: HttpClient: -> Content-Type: application/json; charset=UTF-8
09-11 11:56:31.454 10847-11373/com.algolia.instantsearch.showcase I/System.out: HttpClient: -> Date: Wed, 11 Sep 2019 06:26:31 GMT
09-11 11:56:31.455 10847-11373/com.algolia.instantsearch.showcase I/System.out: HttpClient: -> Server: nginx
09-11 11:56:31.455 10847-11373/com.algolia.instantsearch.showcase I/System.out: HttpClient: -> Timing-Allow-Origin: *
09-11 11:56:31.455 10847-11373/com.algolia.instantsearch.showcase I/System.out: HttpClient: -> Transfer-Encoding: chunked
09-11 11:56:31.455 10847-11373/com.algolia.instantsearch.showcase I/System.out: HttpClient: -> X-Alg-PT: 1
09-11 11:56:31.455 10847-11373/com.algolia.instantsearch.showcase I/System.out: HttpClient: -> X-Android-Received-Millis: 1568183191448
09-11 11:56:31.455 10847-11373/com.algolia.instantsearch.showcase I/System.out: HttpClient: -> X-Android-Response-Source: NETWORK 200
09-11 11:56:31.455 10847-11373/com.algolia.instantsearch.showcase I/System.out: HttpClient: -> X-Android-Selected-Protocol: http/1.1
09-11 11:56:31.455 10847-11373/com.algolia.instantsearch.showcase I/System.out: HttpClient: -> X-Android-Sent-Millis: 1568183191349
09-11 11:56:31.455 10847-11373/com.algolia.instantsearch.showcase I/System.out: HttpClient: -> X-Content-Type-Options: nosniff
09-11 11:56:31.456 10847-11373/com.algolia.instantsearch.showcase I/art: Note: end time exceeds epoch: 
09-11 11:56:31.457 10847-11373/com.algolia.instantsearch.showcase I/art: Note: end time exceeds epoch: 
09-11 11:56:31.461 10847-11373/com.algolia.instantsearch.showcase I/art: Note: end time exceeds epoch: 
09-11 11:56:31.461 10847-11373/com.algolia.instantsearch.showcase I/art: Note: end time exceeds epoch: 
09-11 11:56:31.465 10847-11373/com.algolia.instantsearch.showcase I/art: Note: end time exceeds epoch: 
09-11 11:56:31.466 10847-11373/com.algolia.instantsearch.showcase I/art: Note: end time exceeds epoch: 
09-11 11:56:31.466 10847-11373/com.algolia.instantsearch.showcase I/art: Note: end time exceeds epoch: 
09-11 11:56:31.469 10847-11373/com.algolia.instantsearch.showcase I/art: Note: end time exceeds epoch: 
09-11 11:56:31.469 10847-11373/com.algolia.instantsearch.showcase I/art: Note: end time exceeds epoch: 
09-11 11:56:31.473 10847-11373/com.algolia.instantsearch.showcase I/art: Note: end time exceeds epoch: 
09-11 11:56:31.478 10847-11373/com.algolia.instantsearch.showcase I/art: Note: end time exceeds epoch: 
09-11 11:56:31.482 10847-11373/com.algolia.instantsearch.showcase I/art: Note: end time exceeds epoch: 
09-11 11:56:31.484 10847-11373/com.algolia.instantsearch.showcase I/art: Note: end time exceeds epoch: 
09-11 11:56:31.489 10847-11373/com.algolia.instantsearch.showcase I/art: Note: end time exceeds epoch: 
09-11 11:56:31.492 10847-11373/com.algolia.instantsearch.showcase I/art: Note: end time exceeds epoch: 
09-11 11:56:31.493 10847-11373/com.algolia.instantsearch.showcase I/art: Note: end time exceeds epoch: 
09-11 11:56:31.495 10847-11373/com.algolia.instantsearch.showcase I/art: Note: end time exceeds epoch: 
09-11 11:56:31.497 10847-11373/com.algolia.instantsearch.showcase I/art: Note: end time exceeds epoch: 
09-11 11:56:31.499 10847-11373/com.algolia.instantsearch.showcase I/art: Note: end time exceeds epoch: 
09-11 11:56:31.500 10847-11373/com.algolia.instantsearch.showcase I/art: Note: end time exceeds epoch: 
09-11 11:56:34.272 10847-11349/com.algolia.instantsearch.showcase I/System.out: HttpClient: REQUEST: https://latency-dsn.algolia.net/1/indexes/*/queries
09-11 11:56:34.272 10847-11349/com.algolia.instantsearch.showcase I/System.out: HttpClient: METHOD: HttpMethod(value=POST)
09-11 11:56:34.272 10847-11349/com.algolia.instantsearch.showcase I/System.out: HttpClient: COMMON HEADERS
09-11 11:56:34.272 10847-11349/com.algolia.instantsearch.showcase I/System.out: HttpClient: -> X-Algolia-Application-Id: latency
09-11 11:56:34.272 10847-11349/com.algolia.instantsearch.showcase I/System.out: HttpClient: -> X-Algolia-API-Key: 1f6fd3a6fb973cb08419fe7d288fa4db
09-11 11:56:34.273 10847-11349/com.algolia.instantsearch.showcase I/System.out: HttpClient: -> User-Agent: Android (23); InstantSearchAndroid (2.0.2); Algolia for Kotlin (1.1.4)
09-11 11:56:34.273 10847-11349/com.algolia.instantsearch.showcase I/System.out: HttpClient: -> Accept: application/json
09-11 11:56:34.273 10847-11349/com.algolia.instantsearch.showcase I/System.out: HttpClient: -> Accept-Charset: UTF-8
09-11 11:56:34.273 10847-11349/com.algolia.instantsearch.showcase I/System.out: HttpClient: CONTENT HEADERS
09-11 11:56:34.278 10847-11349/com.algolia.instantsearch.showcase I/art: Note: end time exceeds epoch: 
09-11 11:56:34.433 10847-11349/com.algolia.instantsearch.showcase I/System.out: HttpClient: RESPONSE: 200 OK
09-11 11:56:34.434 10847-11349/com.algolia.instantsearch.showcase I/System.out: HttpClient: METHOD: HttpMethod(value=POST)
09-11 11:56:34.434 10847-11349/com.algolia.instantsearch.showcase I/System.out: HttpClient: FROM: https://latency-dsn.algolia.net/1/indexes/*/queries
09-11 11:56:34.434 10847-11349/com.algolia.instantsearch.showcase I/System.out: HttpClient: COMMON HEADERS
09-11 11:56:34.434 10847-11349/com.algolia.instantsearch.showcase I/System.out: HttpClient: -> Accept-Encoding: deflate, gzip
09-11 11:56:34.434 10847-11349/com.algolia.instantsearch.showcase I/System.out: HttpClient: -> Access-Control-Allow-Origin: *
09-11 11:56:34.434 10847-11349/com.algolia.instantsearch.showcase I/System.out: HttpClient: -> Cache-Control: no-cache
09-11 11:56:34.434 10847-11349/com.algolia.instantsearch.showcase I/System.out: HttpClient: -> Connection: keep-alive
09-11 11:56:34.435 10847-11349/com.algolia.instantsearch.showcase I/System.out: HttpClient: -> Content-Disposition: inline; filename=a.txt
09-11 11:56:34.435 10847-11349/com.algolia.instantsearch.showcase I/System.out: HttpClient: -> Content-Type: application/json; charset=UTF-8
09-11 11:56:34.435 10847-11349/com.algolia.instantsearch.showcase I/System.out: HttpClient: -> Date: Wed, 11 Sep 2019 06:26:34 GMT
09-11 11:56:34.435 10847-11349/com.algolia.instantsearch.showcase I/System.out: HttpClient: -> Server: nginx
09-11 11:56:34.435 10847-11349/com.algolia.instantsearch.showcase I/System.out: HttpClient: -> Timing-Allow-Origin: *
09-11 11:56:34.435 10847-11349/com.algolia.instantsearch.showcase I/System.out: HttpClient: -> Transfer-Encoding: chunked
09-11 11:56:34.435 10847-11349/com.algolia.instantsearch.showcase I/System.out: HttpClient: -> X-Alg-PT: 1
09-11 11:56:34.435 10847-11349/com.algolia.instantsearch.showcase I/System.out: HttpClient: -> X-Android-Received-Millis: 1568183194426
09-11 11:56:34.435 10847-11349/com.algolia.instantsearch.showcase I/System.out: HttpClient: -> X-Android-Response-Source: NETWORK 200
09-11 11:56:34.435 10847-11349/com.algolia.instantsearch.showcase I/System.out: HttpClient: -> X-Android-Selected-Protocol: http/1.1
09-11 11:56:34.436 10847-11349/com.algolia.instantsearch.showcase I/System.out: HttpClient: -> X-Android-Sent-Millis: 1568183194289
09-11 11:56:34.436 10847-11349/com.algolia.instantsearch.showcase I/System.out: HttpClient: -> X-Content-Type-Options: nosniff

**Comment by q-litzler** [comment]
Hello again,

You can now pull the changes fixing the issue on master.

I released a new version of [Instantsearch](https://github.com/algolia/instantsearch-android/releases/tag/2.0.3).

The problem was a threading issue appearing on Marshmallow and lower.

Using `com.algolia:instantsearch-android:2.0.3` should solve the problem.
