### ISSUE TITLE
Fragment viewmodel not loading new data on Fragment.newInstance()

### ISSUE THREAD

**Issue by NainalChauhan** [algolia/instantsearch-android-examples#22]
**Describe the bug 🐛**  
I have a BottomNavigationView with 4 fragments. One of my fragment has been implemented with algolia's instantsearch 2.0.3 using viewmodel and LivePagedListBuilder. I am using paging single index example from your example guide. The searcher loads data correctly when app is opened for the first time, but when I increased the data(by adding new data to the server) suppose from 6 data to 7 data and reload the fragment by calling `fragmentTransaction.replace(R.id.fragment_container, fragment);
        fragmentTransaction.commit();` then it doesn't loads the new set of data instead it still shows the older set of data i.e, 6 data only.

I have noticed one more issue:
I have use LoadingViewSwipeRefreshLayout to refresh the data but when I am pulling the refresh layout  it updated the stats view with 6 to 7 hits but it doesn't refresh the pagedList with the new data.

**To Reproduce 🔍**  
1. Add a new data to server and then reload the fragment.
2. And add a new data to server and then pull the swipe refresh layout to load newly added data.

**Expected behavior 💭**  
It should reload the whole data when navigation to fragment by calling FragmentName.newInstance()

**Screenshots 🖥**  

**Environment:**  
 - OS: Android, version: Marshmallow

**Additional context**

**Comment by q-litzler** [comment]
Hello,

We plan to improve the experience around loading in the near future.

For now you can solve your issue by manually reloading the data when appropriate.

You can do this as follow:

```kotlin
val movies = LivePagedListBuilder(dataSourceFactory, pagedListConfig).build()

movies.value?.dataSource?.invalidate() // This will trigger the dataSource to reload.
```

Also, to make sure the `LoadingViewSwipeRefreshLayout` refreshes the list, please write:

```kotlin
val loading = LoadingConnector(searcher)
val movies = LivePagedListBuilder(dataSourceFactory, pagedListConfig).build()

// When eventReload is triggered, the dataSource is reloaded.
loading.viewModel.eventReload.subscribe {
   movies.value?.dataSource?.invalidate()
}
```

Let us know if this solves the issue.

**Comment by NainalChauhan** [comment]
Hello, 
Thanks for quick response, I have tried your above code to reload data but its not working for me.

I am already using 
`val loading = LoadingConnector(searcher)
val movies = LivePagedListBuilder(dataSourceFactory, pagedListConfig).build()`

**Comment by q-litzler** [comment]
You can share your actual code ?

Thank you

**Comment by NainalChauhan** [comment]
Viewmodel class:
`class PatientViewModel : ViewModel() {
    private val client = ClientSearch(ApplicationID("XXXXXXXX"), APIKey("xxxxxxxxxxxxxxxxxxxx"), LogLevel.ALL)
    private val index = client.initIndex(IndexName(Constants.COLLECTION_PATIENTS))
    public val searcher = SearcherSingleIndex(index)

    val dataSourceFactory = SearcherSingleIndexDataSource.Factory(searcher) {
        it.deserialize(PatientSearch.serializer())
     
    }
    val pagedListConfig = PagedList.Config.Builder().setPageSize(20).setEnablePlaceholders(false).build()
    val patients: LiveData<PagedList<PatientSearch>> = LivePagedListBuilder(dataSourceFactory, pagedListConfig).build()
    val adapterPatient = PatientSearchAdapter()

    val searchBox = SearchBoxConnectorPagedList(searcher, listOf(patients))

    val stats = StatsConnector(searcher)
    val loading = LoadingConnector(searcher)

    val connection = ConnectionHandler()


    /////for filter///////
    private val presCount = Attribute(Constants.FIELD_PRESCRIPTIONCOUNT)
    private val doctorId = Attribute(Constants.FIELD_DOCTOR_ID)
    private val groupPresCount = FilterGroupID(attribute = presCount)
    private val groupDoctorId = FilterGroupID(attribute = doctorId)

    private val mAuth = FirebaseAuth.getInstance()

    private val filters = filters {
        group(groupDoctorId) {
            if (mAuth.currentUser!=null)
                facet(doctorId, mAuth.currentUser!!.uid)
        }
        group(groupPresCount) {
            comparison(presCount, NumericOperator.Greater, 0)
//            range(presCount, IntRange(0, 100))
        }
    }
    private val filterState = FilterState(filters)



    init {
        connection += searchBox
        connection += stats
        connection += loading

        connection += searcher.connectFilterState(filterState)
        connection += filterState.connectPagedList(patients)

    }

    public override fun onCleared() {
        super.onCleared()
        searcher.cancel()
        connection.disconnect()
    }
}`

Fragment code:

`

// the fragment initialization parameters, e.g. ARG_ITEM_NUMBER
private const val ARG_PARAM1 = "param1"
private const val ARG_PARAM2 = "param2"


class PatientSearchFragment : Fragment() {

    private var listener: OnFragmentActionListener? =null
    private var param1: String? = null
    private var param2: String? = null

    private val connection = ConnectionHandler()
    private  var viewModel:PatientViewModel?=null

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        arguments?.let {
            param1 = it.getString(ARG_PARAM1)
            param2 = it.getString(ARG_PARAM2)
        }
    }

    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?,
                              savedInstanceState: Bundle?): View? {
        // Inflate the layout for this fragment
        return inflater.inflate(R.layout.fragment_patient_search, container, false)
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        viewModel = ViewModelProviders.of(requireActivity())[PatientViewModel::class.java]
        val searchBoxView = SearchBoxViewAppCompat(searchView)
        val statsView = StatsTextView(textViewStats)
        val viewSwipeLoading = LoadingViewSwipeRefreshLayout(swipeRefreshLayout)
        viewSwipeLoading.swipeRefreshLayout.setColorSchemeResources(R.color.colorAccent)

       if(viewModel!=null){
           viewModel!!.adapterPatient.setListener(listener)
           viewModel!!.patients.observe(this,
                   Observer {
                       hits -> viewModel!!.adapterPatient.submitList(hits)
                       if (hits.size>0){
                           noData.visibility=View.GONE
                       }else{
                           noData.visibility=View.VISIBLE
                       }
                   }
           )

           connection += viewModel!!.searchBox.connectView(searchBoxView)
           connection += viewModel!!.stats.connectView(statsView, StatsPresenterImpl())
           connection += viewModel!!.loading.connectView(viewSwipeLoading)

           val presenter: StatsPresenter<String> = { response ->
               androidx.core.text.buildSpannedString {
                   if (response != null) {
                       bold { append(response.nbHits.toString()) }
                       append(" ${getString(R.string.results)}")
                   }else
                       append("")
               }.toString()
           }

           connection += viewModel!!.stats.connectView(statsView,  presenter)

           viewModel!!.searcher.error.subscribe {
               if (it != null) {
                   Log.e("TAG", "Error on search: ${it.message}")
                   if(activity!=null) {
                    
                       MySnackbar(activity, it.message.toString(), Snackbar.LENGTH_LONG)
                               .setTextColor(Color.WHITE)
                               .show()
                   }
               }
           }

           recyclerView_Patient.let {
               it.itemAnimator = null
               it.adapter = viewModel!!.adapterPatient
               it.layoutManager = LinearLayoutManager(requireContext())
               it.autoScrollToStart(viewModel!!.adapterPatient)
           }
           viewModel!!.patients.value?.dataSource?.invalidate()
       }
    }


   

    override fun onAttach(context: Context) {
        super.onAttach(context)
        if (context is OnFragmentActionListener) {
            listener = context
        } else {
            throw RuntimeException(context.toString() + " must implement OnFragmentInteractionListener")
        }
    }

    override fun onDetach() {
        super.onDetach()
        listener = null
    }

    override fun onDestroyView() {
        super.onDestroyView()
        if (viewModel!=null) {
            viewModel!!.patients.removeObservers(this)
            viewModel!!.searcher.cancel()
            viewModel!!.onCleared()
            viewModelStore.clear() // I tried clearing viewmodel to load new data on next fragment instance , but it didn't work

        }
        connection.disconnect()
    }


    companion object {
      
        @JvmStatic
        fun newInstance() =
                PatientSearchFragment().apply {
                  
                }
    }
}
`

**Comment by q-litzler** [comment]
In the code you showed, the SwipeRefreshLayout will not update the list if you do not put this code in your `PatientViewModel`:

```kotlin
loading.viewModel.eventReload.subscribe {
   patients.value?.dataSource?.invalidate()
}
```

Other than that, it is not a library bug. Displaying old data means that you were not able to trigger a new HTTP request at the right moment in your application lifecycle. Calling `patients.value?.dataSource?.invalidate()` will do so. You can read more about this [here](https://developer.android.com/reference/android/arch/paging/DataSource).

**Comment by NainalChauhan** [comment]
By adding below code in PatientViewModel now its able to load new data on pull to refresh but after loading the data the swipe progress bar is still visible on screen and the progress bar didn't disappeared and after implementing the below code the StatsTextView doesn't get updated to new count hit, StatsTextView was working fine before implementing the code.
`loading.viewModel.eventReload.subscribe {
   patients.value?.dataSource?.invalidate()
}`

And I am not able to load fresh data on fragment reload. By debugging I found that, it is triggering the line `patients.value?.dataSource?.invalidate()` but doesn't reload the data on fragment load.

**Comment by NainalChauhan** [comment]
Hello,
Thanks for the help, now I am able to refresh the data, both on pull to refresh and fragment load.
I have encountered one more issue, after swipe to refresh search is not working. 

To Reproduce 🔍
Steps to reproduce the behavior:
Search any word from search view, it will work as expected.
Add new data to back-end server and pull the swipe to refresh to load new data.
New data will be loaded.
Now search any word from search view, it will not work and it will not trigger any HTTP query.

**Comment by NainalChauhan** [comment]
Sorry! The issue with search after swipe to refresh was from my side, I was having below code in my fragment. After removing the viewmodel code part from this method it worked.

```
override fun onDestroyView() {
        super.onDestroyView()
        if (viewModel!=null) {
            viewModel!!.patients.removeObservers(this)
            viewModel!!.searcher.cancel()
            viewModel!!.onCleared()
            viewModelStore.clear()

        }
        connection.disconnect()
    }
```
